### ISSUE TITLE
cards won't use the whole area available

### ISSUE THREAD

**Issue by iroQuai** [LRvdLinden/weather_dd_addon#1]
first: thanks for the hard work! impressive weather page this way :)
Seems to work like it should, only one thing: 
it doesn't take advantage of the whole screen!
check this screenshot: https://imgur.com/a/H3We5nW

any idea how to fix this?

**Comment by LRvdLinden** [comment]
Hi, thanks!

Do you have this issue also at the other map views?

**Comment by iroQuai** [comment]
Yeah, it's the same on every view

Op di 28 dec. 2021 22:33 schreef LRvdLinden ***@***.***>:

**Comment by LRvdLinden** [comment]
I see that it is a change in 2021.12.+ I will fix it soon.

**Comment by iroQuai** [comment]
thanks! i'll just wait for that then :)

Op wo 29 dec. 2021 om 17:46 schreef LRvdLinden ***@***.***>:

**Comment by Sazelish** [comment]
I have the same issue on my browser. But they do show up on my mobile phone.

**Comment by LRvdLinden** [comment]
See the solution for this issue https://github.com/dwainscheeren/dwains-dashboard-addons/issues/138#issuecomment-1005097409
